/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mywebfactory.dbtools.gui;

import com.mywebfactory.dbtools.oracle.OracleQueries;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mywebfactory.objects.connectionObj;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;

/**
 *
 * @author Paul
 */
public class DBScriptPanel extends javax.swing.JPanel {

    private connectionObj conObj;
    private DBVisualizerPanel dbMainPanel;
    private String triggerName;

    public DBScriptPanel(String triggerName, connectionObj conObj, DBVisualizerPanel dbMainPanel) {
        initComponents();
        this.conObj = conObj;
        this.dbMainPanel = dbMainPanel;
        this.triggerName = triggerName;

        rSyntaxTextArea1.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_SQL);
        rSyntaxTextArea1.setCodeFoldingEnabled(true);
        rSyntaxTextArea1.setAntiAliasingEnabled(true);

    }

    public void showData() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                dbMainPanel.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

                if (conObj.getDbType().toUpperCase().equals("ORACLE")) {
                    try {
                        ResultSet rsa = OracleQueries.getTriggerScript(triggerName, conObj);
                        rSyntaxTextArea1.setText("CREATE OR REPLACE TRIGGER ");
                        while (rsa.next()) {
                            System.out.println(rsa.getString(2).toString());
                            rSyntaxTextArea1.setText(rSyntaxTextArea1.getText() + rsa.getString(1).toString());
                            rSyntaxTextArea1.setText(rSyntaxTextArea1.getText() + rsa.getString(2).toString());
                        }

                        dbMainPanel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    } catch (SQLException ex) {
                        Logger.getLogger(DBScriptPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rTextScrollPane1 = new org.fife.ui.rtextarea.RTextScrollPane();
        rSyntaxTextArea1 = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();

        rSyntaxTextArea1.setColumns(20);
        rSyntaxTextArea1.setRows(5);
        rTextScrollPane1.setViewportView(rSyntaxTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rTextScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(rTextScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.fife.ui.rsyntaxtextarea.RSyntaxTextArea rSyntaxTextArea1;
    private org.fife.ui.rtextarea.RTextScrollPane rTextScrollPane1;
    // End of variables declaration//GEN-END:variables
}
