/*
 * Andjety 2.0 - Code by Paul Coiffier - 2012/2013
 * 
 */
package com.mobissime.andjety.dialogs;

import com.mobissime.andjety.utils.OptionsParser;
import com.mobissime.andjety.utils.WriteOptionsXML;
import com.mobissime.andjety.MainFen;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Paul Coiffier
 */
public class OptionsDialog extends javax.swing.JDialog {

    /**
     * Creates new form OptionsDialog
     */
    private MainFen mf;

    public OptionsDialog(java.awt.Frame parent, boolean modal, MainFen mf) {
        super(parent, modal);

        JFrame.setDefaultLookAndFeelDecorated(true);


        initComponents();
        this.mf = mf;

        jTabbedPane1.remove(jPanel2);
        String skinName = null;
        OptionsParser optionsParse = new OptionsParser();
        optionsParse.parseXml();

        /*
         * jTextFieldMysql_password.setText(optionsParse.password);
         * jTextFieldMysql_user.setText(optionsParse.user);
         * jTextFieldMysql_serveur.setText(optionsParse.serveur);
         *
         */
        if (optionsParse.majOnStartup.equals("oui")) {
            jCheckBoxMAJ.setSelected(true);
        } else {
            jCheckBoxMAJ.setSelected(false);
        }

        if (optionsParse.majAstuceOnStartup.equals("oui")) {
            jCheckBoxMAJAstuce.setSelected(true);
        } else {
            jCheckBoxMAJAstuce.setSelected(false);
        }


        skinName = optionsParse.skinName;

        jComboBox1.removeAllItems();
        jComboBox1.addItem("AutumnLookAndFeel");
        jComboBox1.addItem("BusinessBlackSteelLookAndFeel");
        jComboBox1.addItem("BusinessBlueSteelLookAndFeel");
        jComboBox1.addItem("BusinessLookAndFeel");
        jComboBox1.addItem("ChallengerDeepLookAndFeel");
        jComboBox1.addItem("CremeCoffeeLookAndFeel");
        jComboBox1.addItem("CremeLookAndFeel");
        jComboBox1.addItem("DustCoffeeLookAndFeel");
        jComboBox1.addItem("DustLookAndFeel");
        jComboBox1.addItem("EmeraldDuskLookAndFeel");
        jComboBox1.addItem("MagmaLookAndFeel");
        jComboBox1.addItem("MistAquaLookAndFeel");
        jComboBox1.addItem("MistSilverLookAndFeel");
        jComboBox1.addItem("ModerateLookAndFeel");
        jComboBox1.addItem("NebulaBrickWallLookAndFeel");
        jComboBox1.addItem("NebulaLookAndFeel");
        jComboBox1.addItem("OfficeBlue2007LookAndFeel");
        jComboBox1.addItem("OfficeSilver2007LookAndFeel");
        jComboBox1.addItem("RavenGraphiteGlassLookAndFeel");
        jComboBox1.addItem("RavenGraphiteLookAndFeel");
        jComboBox1.addItem("RavenLookAndFeel");
        jComboBox1.addItem("SaharaLookAndFeel");
        jComboBox1.addItem("TwilightLookAndFeel");

        jComboBox1.setSelectedItem(skinName);
        jComboBox2.setSelectedItem(optionsParse.languageValue);

    }

    public void Appliquer() {

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    //SubstanceLookAndFeel.setSkin("org.pushingpixels.substance.api.skin.Substance" + jComboBox1.getSelectedItem().toString());
                    UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.Substance" + jComboBox1.getSelectedItem().toString());
                } catch (Exception e) {
                    System.out.println("Erreur : " + e.toString());
                }
            }
        });
    }

    public void WriteOptions() {
        WriteOptionsXML saveOptions = new WriteOptionsXML();
        String updateStr = "";
        String updateStrAstuce = "";

        if (jCheckBoxMAJ.isSelected()) {
            updateStr = "oui";
        } else {
            updateStr = "non";
        }

        if (jCheckBoxMAJAstuce.isSelected()) {
            updateStrAstuce = "oui";
        } else {
            updateStrAstuce = "non";
        }

        saveOptions.WriteOptionsFile(jTextFieldMysql_user.getText(), jTextFieldMysql_password.getText(), jTextFieldMysql_serveur.getText(), jComboBox1.getSelectedItem().toString(), updateStr, updateStrAstuce, jComboBox2.getSelectedItem().toString());
        this.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBoxMAJAstuce = new javax.swing.JCheckBox();
        jCheckBoxMAJ = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMysql_serveur = new javax.swing.JTextField();
        jTextFieldMysql_user = new javax.swing.JTextField();
        jTextFieldMysql_password = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Theme : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBoxMAJAstuce.setText("Afficher l'astuce du jour au démarrage");
        jCheckBoxMAJAstuce.setEnabled(false);

        jCheckBoxMAJ.setText("Vérifier les mises à jour à chaque démarrage");
        jCheckBoxMAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMAJActionPerformed(evt);
            }
        });

        jButton6.setText("Clear database list");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Language : ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Français" }));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow_refresh.png"))); // NOI18N
        jButton2.setText("Apply");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxMAJ)
                    .addComponent(jCheckBoxMAJAstuce)
                    .addComponent(jButton6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jCheckBoxMAJAstuce)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxMAJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Général", jPanel3);

        jPanel2.setEnabled(false);

        jLabel2.setText("Serveur Mysql : ");

        jLabel3.setText("Utilisateur : ");

        jLabel4.setText("Mot de passe : ");

        jTextFieldMysql_serveur.setEnabled(false);

        jTextFieldMysql_user.setEnabled(false);

        jTextFieldMysql_password.setEnabled(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/database_gear.png"))); // NOI18N
        jButton4.setText("Créer la base de données");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/database_save.png"))); // NOI18N
        jButton5.setText("Exporter la base de données");
        jButton5.setEnabled(false);
        jButton5.setFocusPainted(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMysql_password, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addComponent(jTextFieldMysql_serveur)
                            .addComponent(jTextFieldMysql_user)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldMysql_serveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMysql_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMysql_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Base MySQL", jPanel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tick.png"))); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/gnome_preferences_other.png"))); // NOI18N
        jLabel5.setText("Settings");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jSeparator1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Si la langue à changée alors on alerte qu'il faut redémarrer Andjety

        OptionsParser optionsParse = new OptionsParser();
        optionsParse.parseXml();
        if (!jComboBox2.getSelectedItem().toString().equals(optionsParse.languageValue)) {
            JOptionPane.showMessageDialog(this, "Veuillez quitter et relancer Andjety afin que le changement de langue soit opéré.", "Andjety", JOptionPane.INFORMATION_MESSAGE);
        }
        WriteOptions();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Appliquer();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


        //Custom button text
        Object[] options = {"Oui",
            "Non"};
        int response = JOptionPane.showOptionDialog(null, "Etes-vous sur de vouloir créer la base de données ?",
                "Quitter",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[1]);

        if (response == 0) {

            // On enregistre les paramètres
            WriteOptionsXML saveOptions = new WriteOptionsXML();

            String updateStr = "";
            String updateStrAstuce = "";

            if (jCheckBoxMAJ.isSelected()) {
                updateStr = "oui";
            } else {
                updateStr = "non";
            }

            if (jCheckBoxMAJAstuce.isSelected()) {
                updateStrAstuce = "oui";
            } else {
                updateStrAstuce = "non";
            }

            saveOptions.WriteOptionsFile(jTextFieldMysql_user.getText(), jTextFieldMysql_password.getText(), jTextFieldMysql_serveur.getText(), jComboBox1.getSelectedItem().toString(), updateStr, updateStrAstuce, jComboBox2.getSelectedItem().toString());

            // Appel ScriptRunner
            //MysqlConnexion mscon = new MysqlConnexion();
            //Connection con = mscon.getMysqlCon();
            /*String path = System.getProperty("user.dir").toString();
            File file = new File(path + "/Files/andjety.sql");*/
            //ScriptRunner runner = new ScriptRunner(con, false, false);
            //runner.runScript(new BufferedReader(new FileReader(file)));

            JOptionPane.showMessageDialog(this, "Base de donnée créée ! Veuillez redémarrer Andjety", "Andjety", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBoxMAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMAJActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Object[] options = {"Oui",
            "Non"};
        int response = JOptionPane.showOptionDialog(null, "Etes-vous sur de vouloir purger la liste des serveurs ? Cela aura pour effet de supprimer l'ensemble des bases de données de la liste.",
                "Quitter",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options, options[1]);

        if (response == 0) {
            mf.purgeDatabaseArray();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBoxMAJ;
    private javax.swing.JCheckBox jCheckBoxMAJAstuce;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldMysql_password;
    private javax.swing.JTextField jTextFieldMysql_serveur;
    private javax.swing.JTextField jTextFieldMysql_user;
    // End of variables declaration//GEN-END:variables
}
